CREATE DATABASE IF NOT EXISTS WORLD_POPULATION;

CREATE SCHEMA IF NOT EXISTS WORLD_POPULATION.RAW;
CREATE SCHEMA IF NOT EXISTS WORLD_POPULATION.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS WORLD_POPULATION.REPORTING;

CREATE WAREHOUSE IF NOT EXISTS WORLD_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE DATABASE WORLD_POPULATION;
USE WAREHOUSE WORLD_WH;
