CREATE DATABASE if not exists Retail_Pipeline;

CREATE SCHEMA IF NOT EXISTS RETAIL_PIPELINE.RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_PIPELINE.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS RETAIL_PIPELINE.REPORTING;

CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE RETAIL_PIPELINE;
USE warehouse retail_wh;
