USE DATABASE RETAIL_PIPELINE;
USE SCHEMA RAW;
USE WAREHOUSE RETAIL_WH;

CREATE STAGE IF NOT EXISTS raw_stage
  FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
  );

LIST @raw_stage;
